# Generated by Django 3.2.18 on 2023-07-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.DateField(verbose_name='Fecha de Envío')),
                ('destinatario', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de Envío')),
                ('seguimiento', models.CharField(max_length=15, verbose_name='Número de Seguimiento')),
                ('acuse', models.FileField(blank=True, null='True', upload_to='', verbose_name='Acuse de Recibo')),
            ],
        ),
    ]
