# Generated by Django 4.1.3 on 2023-09-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.DateField(verbose_name='Fecha de Envío')),
                ('destinatario', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de Envío')),
                ('seguimiento', models.CharField(max_length=15, verbose_name='Número de Seguimiento')),
                ('acuse', models.CharField(blank=True, max_length=33, null='True', verbose_name='Acuse de Recibo')),
            ],
        ),
    ]
