# Generated by Django 4.2.1 on 2023-07-20 18:10

import correo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='acuse',
        ),
        migrations.AddField(
            model_name='correo',
            name='Acuse_de_Recibo',
            field=models.FileField(blank=True, null='True', upload_to='', verbose_name=correo.models.subida_documentacion),
            preserve_default='True',
        ),
    ]
