# Generated by Django 4.2.1 on 2023-07-20 18:18

import correo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_remove_correo_acuse_correo_acuse_de_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='Acuse_de_Recibo',
            field=models.FileField(blank=True, null='True', upload_to=correo.models.subida_documentacion, verbose_name='Número de Seguimiento'),
        ),
    ]
