# Generated by Django 4.2.1 on 2023-07-20 18:20

import correo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0003_alter_correo_acuse_de_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='Acuse_de_Recibo',
        ),
        migrations.AddField(
            model_name='correo',
            name='acuse',
            field=models.FileField(blank=True, null='True', upload_to=correo.models.subida_documentacion, verbose_name='Acuse de Recibo'),
            preserve_default='True',
        ),
    ]
