# Generated by Django 4.1.3 on 2023-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0003_correo_carnet_alter_correo_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='seguimiento',
            field=models.CharField(max_length=30, verbose_name='Número de Seguimiento'),
        ),
    ]
