# Generated by Django 3.2.18 on 2023-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0004_remove_correo_acuse_de_recibo_correo_acuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correo',
            name='destinatario',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
    ]
