# Generated by Django 4.1.3 on 2023-10-18 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0004_alter_correo_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='correo',
            name='acuse',
            field=models.CharField(blank=True, max_length=33, null='True', verbose_name='Número'),
        ),
    ]
