# Generated by Django 4.1.3 on 2023-10-18 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0005_correo_año_acuse_alter_correo_acuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número'),
        ),
    ]
