# Generated by Django 4.1.3 on 2023-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0006_alter_correo_acuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='finalizado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=43, null='True', verbose_name='Finalizado'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='correo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null='True', verbose_name='Teléfono'),
        ),
    ]
