# Generated by Django 4.1.3 on 2023-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0007_correo_finalizado_alter_correo_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='Se guarda en Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
