# Generated by Django 4.1.3 on 2023-11-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0008_correo_se guarda en caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correo',
            old_name='Se guarda en Caja',
            new_name='Caja',
        ),
    ]
