# Generated by Django 4.1.3 on 2023-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0009_rename_se guarda en caja_correo_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='Caja',
        ),
        migrations.AddField(
            model_name='correo',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
    ]
