# Generated by Django 4.2.4 on 2024-11-08 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0010_remove_correo_caja_correo_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='finalizado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=43, null=True, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
