# Generated by Django 4.1.3 on 2023-10-19 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guionista',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='guionista',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='guionista',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='guionista',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='guionista',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='año_certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='año_certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='año_certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='año_certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='año_acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='año_acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='año_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='año_formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='año_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='guionista',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='certificado',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='acta',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='acuse',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='formulario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='secundario',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
    ]
