# Generated by Django 3.2.18 on 2023-05-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locutor_local',
            name='pdf_secundario',
            field=models.FileField(blank=True, null='True', upload_to='documentación'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='pdf_secundario',
            field=models.FileField(blank=True, null='True', upload_to='documentación'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='pdf_secundario',
            field=models.FileField(blank=True, null='True', upload_to='documentación'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='pdf_secundario',
            field=models.FileField(blank=True, null='True', upload_to='documentación'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
