# Generated by Django 3.2.18 on 2023-08-29 22:17

import Base_datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0002_auto_20230829_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='acuse',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acuse'),
        ),
    ]
