# Generated by Django 4.1.3 on 2023-11-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0002_guionista_año_acta_guionista_año_acuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guionista',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='Caja',
            field=models.CharField(blank=True, max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
