# Generated by Django 4.1.3 on 2023-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0003_guionista_caja_locutor_local_caja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guionista',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='locutor_local',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='locutor_nacional',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_local_planta',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_local_radio',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_local_tv',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_nacional_planta',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_nacional_radio',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='operador_nacional_tv',
            name='Caja',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='Caja',
        ),
        migrations.AddField(
            model_name='guionista',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_nacional',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_planta',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_radio',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_nacional_tv',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='productor',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Caja'),
            preserve_default='True',
        ),
    ]
