# Generated by Django 4.1.3 on 2023-09-27 05:32

import Base_datos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0004_auto_20230829_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guionista',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='certificado',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='certificado',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='certificado',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='certificado',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='DNI',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='acta',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año del Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='formulario',
            field=models.FileField(blank=True, null='True', upload_to=Base_datos.models.subida_documentacion, verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='habilitación',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_disposición',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de la Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_expediente',
            field=models.IntegerField(blank=True, null='True', validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número del Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='secundario',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Secundario'),
        ),
    ]
