# Generated by Django 4.1.3 on 2023-09-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0005_alter_guionista_dni_alter_guionista_acta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guionista',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='locutor_local',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='locutor_nacional',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_local_planta',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_local_radio',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_local_tv',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_nacional_planta',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_nacional_radio',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='operador_nacional_tv',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
        migrations.AlterModelOptions(
            name='productor',
            options={'permissions': [('view_complete_and_incomplete', 'view complete and incomplete')]},
        ),
    ]
