# Generated by Django 4.1.3 on 2024-05-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0008_alter_guionista_chequeo_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locutor_local',
            name='inicio_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='locutor_local',
            name='reclamo_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='inicio_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_planta',
            name='reclamo_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='inicio_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_radio',
            name='reclamo_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='inicio_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='operador_local_tv',
            name='reclamo_tad',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
    ]
