# Generated by Django 4.2.4 on 2024-11-08 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_datos', '0010_guionista_observaciones_locutor_local_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guionista',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='guionista',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='chequeo_certi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='inicio_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='reclamo_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_local',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='locutor_nacional',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='chequeo_certi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='inicio_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='reclamo_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_planta',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='chequeo_certi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='inicio_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='reclamo_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_radio',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='certificado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Certificado Laboral'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='chequeo_certi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='inicio_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='reclamo_tad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_local_tv',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_planta',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_radio',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='operador_nacional_tv',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='DNI',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Documento N°'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acta de Examen'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_acta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acta'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_acuse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año DNI'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Formulario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='año_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='chequeo_dni',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='chequeo_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='chequeo_formulario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='chequeo_insti',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='chequeo_secu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='formulario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Formulario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='habilitación',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Habilitación'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='instituto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Egresado de'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_disposición',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Disposición'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='número_expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Expediente'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_dni',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - D.N.I.'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_instituto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Analítico del Instituto'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='pdf_secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Número GDE - Secundario'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='secundario',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año Secundario'),
        ),
    ]
