# Generated by Django 4.1.3 on 2023-11-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='carrera',
            field=models.CharField(choices=[('Locutor/a Nacional', 'Locutor/a Nacional'), ('Operador/a Nacional de Radio', 'Operador/a Nacional de Radio'), ('Operador/a Nacional de TV', 'Operador/a Nacional de TV'), ('Operador/a Nacional de Planta Transmisora', 'Operador/a Nacionales de Planta Transmisora'), ('Productor/a y Director/a para Radio y TV', 'Productor/a y Director/a para Radio y TV'), ('Guionista de Radio y TV', 'Guionista de Radio y TV')], default=0, max_length=100, verbose_name='Carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='examen',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Habilitación', 'Habilitación')], default=1, max_length=50, verbose_name='Examen'),
            preserve_default=False,
        ),
    ]
