# Generated by Django 4.1.3 on 2023-11-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_acta_carrera_acta_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='dni1',
            field=models.CharField(max_length=10, verbose_name='D.N.I. alumno 1'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni10',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 10'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni11',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 11'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni12',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 12'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni13',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 13'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni14',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 14'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni15',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 15'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni16',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 16'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni17',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 17'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni18',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 18'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni19',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 19'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni2',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 2'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni20',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 20'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni21',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 21'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni22',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 22'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni23',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 23'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni24',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 24'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni25',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 25'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni3',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 3'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni4',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 4'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni5',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 5'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni6',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 6'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni7',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 7'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni8',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 8'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni9',
            field=models.CharField(blank=True, max_length=10, null='True', verbose_name='D.N.I. alumno 9'),
        ),
    ]
