# Generated by Django 4.2.1 on 2024-05-23 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Libros', '0003_firma_nombre_alter_firma_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='firma',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to=settings.AUTH_USER_MODEL),
        ),
    ]
