# Generated by Django 4.1.3 on 2024-03-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_alter_acta_firma1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='firma1',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='acta_firma1', to='Libros.firma'),
        ),
    ]
