# Generated by Django 4.2.1 on 2024-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_remove_firma_nombre_alter_firma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='nombre',
            field=models.CharField(default=0, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firma',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
    ]
