# Generated by Django 4.2.1 on 2024-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0006_rename_user_firma_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='profesores',
        ),
        migrations.AddField(
            model_name='acta',
            name='profesor1',
            field=models.CharField(default=0, max_length=100, verbose_name='Profesor1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='profesor2',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Profesor2'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='acta',
            name='profesor3',
            field=models.CharField(blank=True, max_length=100, null='True', verbose_name='Profesor3'),
            preserve_default='True',
        ),
    ]
