# Generated by Django 4.2.4 on 2024-11-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0008_alter_acta_aprobados_alter_acta_ausentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='dni10',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 10'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni11',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 11'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni12',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 12'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni13',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 13'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni14',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 14'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni15',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 15'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni16',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 16'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni17',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 17'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni18',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 18'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni19',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 19'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 2'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni20',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 20'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni21',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 21'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni22',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 22'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni23',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 23'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni24',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 24'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni25',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 25'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 3'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 4'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 5'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 6'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni7',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 7'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni8',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 8'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dni9',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='D.N.I. alumno 9'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='firma1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta_firma1', to='Libros.firma'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='firma2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta_firma2', to='Libros.firma'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='firma3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta_firma3', to='Libros.firma'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota10',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 10'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota11',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 11'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota12',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 12'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota13',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 13'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota14',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 14'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota15',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 15'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota16',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 16'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota17',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 17'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota18',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 18'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota19',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 19'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota2',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 2'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota20',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 20'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota21',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 21'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota22',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 22'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota23',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 23'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota24',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 24'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota25',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 25'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota3',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 3'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota4',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 4'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota5',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 5'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota6',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 6'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota7',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 7'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota8',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 8'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nota9',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('DESAPROBADO', 'DESAPROBADO'), ('AUSENTE', 'AUSENTE'), ('1 (Uno con 00/100)', '1 (Uno con 00/100)'), ('1,50 (Uno con 50/100)', '1,50 (Uno con 50/100)'), ('2 (Dos con 00/100)', '2 (Dos con 00/100)'), ('2,50 (Dos con 50/100)', '2,50 (Dos con 50/100)'), ('3 (Tres con 00/100)', '3 (Tres con 00/100)'), ('3,50 (Tres con 50/100)', '3,50 (Tres con 50/100)'), ('4 (Cuatro con 00/100)', '4 (Cuatro con 00/100)'), ('4,50 (Cuatro con 50/100)', '4,50 (Cuatro con 50/100)'), ('5 (Cinco con 00/100)', '5 (Cinco con 00/100)'), ('5,50 (Cinco con 50/100)', '5,50 (Cinco con 50/100)'), ('6 (Seis con 00/100)', '6 (Seis con 00/100)'), ('6,50 (Seis con 50/100)', '6,50 (Seis con 50/100)'), ('7 (Siete con 00/100)', '7 (Siete con 00/100)'), ('7,50 (Siete con 50/100)', '7,50 (Siete con 50/100)'), ('8 (Ocho con 00/100)', '8 (Ocho con 00/100)'), ('8,50 (Ocho con 50/100)', '8,50 (Ocho con 50/100)'), ('9 (Nueve con 00/100)', '9 (Nueve con 00/100)'), ('9,50 (Nueve con 50/100)', '9,50 (Nueve con 50/100)'), ('10 (Diez con 00/100)', '10 (Diez con 00/100)')], max_length=100, null=True, verbose_name='Nota alumno 9'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 10'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona11',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 11'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 12'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona13',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 13'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona14',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 14'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona15',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 15'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona16',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 16'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona17',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 17'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona18',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 18'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona19',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 19'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 2'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona20',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 20'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona21',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 21'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona22',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 22'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona23',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 23'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona24',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 24'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona25',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 25'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 3'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 4'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 5'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 6'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 7'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 8'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='persona9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alumno 9'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='profesor2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesor2'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='profesor3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesor3'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='firmas'),
        ),
    ]
