from django.db import models
from django.contrib.auth.models import User

class Locutor_nacional(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)

class Locutor_local(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    dni = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    localidad = models.CharField(max_length=100, null='True', blank=True)
    provincia = models.CharField(max_length=100, null='True', blank=True)
    certificado = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitacion = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposicion = models.CharField(max_length=100, null='True', blank=True)

class Operador_nacional_radio(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)

class Operador_nacional_tv(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)

class Operador_nacional_planta(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)

class Operador_local_radio(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    dni = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    localidad = models.CharField(max_length=100, null='True', blank=True)
    provincia = models.CharField(max_length=100, null='True', blank=True)
    certificado = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitacion = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposicion = models.CharField(max_length=100, null='True', blank=True)

class Operador_local_tv(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    dni = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    localidad = models.CharField(max_length=100, null='True', blank=True)
    provincia = models.CharField(max_length=100, null='True', blank=True)
    certificado = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitacion = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposicion = models.CharField(max_length=100, null='True', blank=True)

class Operador_local_planta(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    dni = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    localidad = models.CharField(max_length=100, null='True', blank=True)
    provincia = models.CharField(max_length=100, null='True', blank=True)
    certificado = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitacion = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposicion = models.CharField(max_length=100, null='True', blank=True)

class Productor(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)

class Guionista(models.Model):
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    formulario = models.FileField(upload_to='documentación', null='True', blank=True)
    DNI = models.CharField(max_length=9, null='True', blank=True)
    pdf_dni = models.FileField(upload_to='documentación', null='True', blank=True)
    secundario = models.CharField(max_length=100, null='True', blank=True)
    pdf_secundario = models.FileField(upload_to='documentación', null='True', blank=True)
    instituto = models.CharField(max_length=100, null='True', blank=True)
    pdf_instituto = models.FileField(upload_to='documentación', null='True', blank=True)
    acta = models.FileField(upload_to='documentación', null='True', blank=True)
    habilitación = models.CharField(max_length=9, null='True', blank=True)
    expediente = models.CharField(max_length=100, null='True', blank=True)
    disposición = models.CharField(max_length=100, null='True', blank=True)