# Generated by Django 3.2.18 on 2023-05-24 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Año_de_Expediente', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Número_de_Expediente', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Fecha_de_Creación', models.DateTimeField(verbose_name='%d/%m/%Y')),
                ('Cantidad_de_Habilitados', models.IntegerField()),
                ('Instituto_o_Localidad', models.CharField(max_length=100)),
                ('Categoría', models.CharField(choices=[('LN', 'Locutores Nacionales'), ('LL', 'Locutores Locales'), ('OPNV', 'Operadores Nacionales Varios'), ('OPRN', 'Operadores Nacionales de Radio'), ('OPTVN', 'Operadores Nacionales de TV'), ('OPPTN', 'Operadores Nacionales de Planta Transmisora'), ('OPLV', 'Operadores Locales Varios'), ('OPRN', 'Operadores Locales de Radio'), ('OPTVN', 'Operadores Locales de TV'), ('OPPTN', 'Operadores Locales de Planta Transmisora'), ('PROD', 'Productores y Directores para Radio y TV'), ('GUION', 'Guionistas de Radio y TV')], max_length=5)),
                ('Fecha_de_disposición', models.DateTimeField(blank=True, null='True')),
                ('Estado', models.CharField(choices=[('R.I.', 'Revisión ISER'), ('DNSA', 'Revisión DNSA'), ('DGAJR', 'Esperando Dictamen'), ('DISPO', 'Esperando Firma de Disposición'), ('FIN', 'Finalizado')], max_length=5)),
            ],
        ),
    ]
