# Generated by Django 3.2.18 on 2023-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Fecha_de_Creación',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Fecha_de_disposición',
            field=models.DateField(blank=True, null='True'),
        ),
    ]
