# Generated by Django 3.2.18 on 2023-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_auto_20230524_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Categoría',
            field=models.CharField(choices=[('Locutores Nacionales', 'Locutores Nacionales'), ('Locutores Locales', 'Locutores Locales'), ('Operadores Nacionales Varios', 'Operadores Nacionales Varios'), ('Operadores Nacionales de Radio', 'Operadores Nacionales de Radio'), ('Operadores Nacionales de TV', 'Operadores Nacionales de TV'), ('Operadores Nacionales de Planta Transmisora', 'Operadores Nacionales de Planta Transmisora'), ('Operadores Locales Varios', 'Operadores Locales Varios'), ('Operadores Locales de Radio', 'Operadores Locales de Radio'), ('Operadores Locales de TV', 'Operadores Locales de TV'), ('Operadores Locales de Planta Transmisora', 'Operadores Locales de Planta Transmisora'), ('Productores y Directores para Radio y TV', 'Productores y Directores para Radio y TV'), ('Guionistas de Radio y TV', 'Guionistas de Radio y TV')], max_length=43),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Estado',
            field=models.CharField(choices=[('Revisión ISER', 'Revisión ISER'), ('Revisión DNSA', 'Revisión DNSA'), ('Esperando Dictamen', 'Esperando Dictamen'), ('Firma de Disposición', 'Firma de Disposición'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
    ]
