# Generated by Django 3.2.18 on 2023-09-04 21:29

from django.db import migrations, models
import expedientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_auto_20230524_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Número_de_Expediente',
            field=models.CharField(max_length=9, validators=[expedientes.models.validar_numero]),
        ),
    ]
