# Generated by Django 3.2.18 on 2023-09-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_alter_expediente_número_de_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Estado',
            field=models.CharField(choices=[('Armado ISER', 'Armado ISER'), ('Revisión ISER', 'Revisión ISER'), ('Revisión DNSA', 'Revisión DNSA'), ('Esperando Dictamen', 'Esperando Dictamen'), ('Firma de Disposición', 'Firma de Disposición'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
    ]
