# Generated by Django 3.2.18 on 2023-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_alter_expediente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Fecha_de_Creación',
            field=models.DateField(verbose_name='Fecha de Caratulación'),
        ),
    ]
