# Generated by Django 4.1.3 on 2024-05-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_expediente_fecha_de_creación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Estado',
            field=models.CharField(choices=[('Armado ISER', 'Armado ISER'), ('Revisión ISER', 'Revisión ISER'), ('Revisión DNSA', 'Revisión DNSA'), ('Esperando Dictamen', 'Esperando Dictamen'), ('Firma de Disposición', 'Firma de Disposición'), ('Hacer carnet', 'Hacer carnet'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
    ]
