# Generated by Django 4.2.4 on 2024-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_alter_expediente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='observaciones',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
    ]
