# Generated by Django 4.2.4 on 2024-11-08 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedientes', '0008_expediente_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
