# Generated by Django 5.1.3 on 2024-12-26 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_expediente_usuario_alter_expediente_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='aprobados',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_asignado',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_pase',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Fecha_de_disposición',
            field=models.DateField(blank=True, null=True),
        ),
    ]
