# Generated by Django 5.1.3 on 2024-12-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_expediente_aprobados_expediente_fecha_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_pase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
