# Generated by Django 5.1.3 on 2024-12-26 19:02

import django.core.validators
import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_alter_expediente_fecha_pase'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='pase_legal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Año_de_Expediente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Cantidad_de_Habilitados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Fecha_de_Creación',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caratulación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='Número_de_Expediente',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[expedientes.models.validar_numero]),
        ),
    ]
